{{- if ne .Values.schedule.cleanupExposure "" }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cleanup-exposure
  labels:
    component: cleanup-exposure
    app: exposure-notifications-server
spec:
  schedule: {{ .Values.schedule.cleanupExposure | quote }}
  jobTemplate:
    metadata:
      labels:
        component: cleanup-exposure
        app: exposure-notifications-server
    spec:
      template:
        spec:
          containers:
          - name: cleanup-exposure
            image: curlimages/curl
            args:
              - /bin/sh
              - -c
              - date; curl -X POST http://cleanup-exposure/
            resources:
              requests:
                cpu: "1m"
                memory: "40Mi"
              limits:
                cpu: "2m"
                memory: "80Mi"
          restartPolicy: OnFailure
{{- end }}
