{{- if .Values.federation }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: federationin
  labels:
    component: federationin
    app: exposure-notifications-server
spec:
  replicas: 1
  selector:
    matchLabels:
      component: federationin
      app: exposure-notifications-server
  template:
    metadata:
      labels:
        component: federationin
        app: exposure-notifications-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: federationin
        image: {{ .Values.image.registry }}/federationin:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pull_policy }}
        ports:
          - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
          - name: RPC_TIMEOUT
            value: "10m"
          - name: TRUNCATE_WINDOW
            value: "1h"
          - name: TLS_SKIP_VERIFY
            value: "false"
          - name: TLS_CERT_FILE
            value: ""
          - name: CREDENTIALS_FILE
            value: ""
{{ include "exposure-notification.observability-exporter" . | indent 10 }}
{{ include "exposure-notification.database" . | indent 10 }}
{{ include "exposure-notification.secrets-management" . | indent 10 }}
{{- if .Values.azure }}
{{ include "exposure-notification.azure-service-principal" . | indent 10 }}
{{- end }}
{{- end }}
