{{- if .Values.cleanupExposure }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cleanup-exposure
  labels:
    component: cleanup-exposure
    app: exposure-notifications-server
spec:
  replicas: 1
  selector:
    matchLabels:
      component: cleanup-exposure
      app: exposure-notifications-server
  template:
    metadata:
      labels:
        component: cleanup-exposure
        app: exposure-notifications-server
    spec:
      containers:
      - name: cleanup-exposure
        image: {{ .Values.image.registry }}/cleanup-exposure:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pull_policy | quote }}
        ports:
          - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
          - name: CLEANUP_TIMEOUT
            value: "10m"
          - name: CLEANUP_TTL
            value: "336h"
{{ include "exposure-notification.blob-storage" . | indent 10 }}
{{ include "exposure-notification.database" . | indent 10 }}
{{ include "exposure-notification.secrets-management" . | indent 10 }}
{{- if .Values.azure }}
{{ include "exposure-notification.azure-service-principal" . | indent 10 }}
{{- end }}
{{- end }}
