{{- if .Values.cleanupExport }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cleanup-export
  labels:
    component: cleanup-export
    app: exposure-notifications-server
spec:
  replicas: 1
  selector:
    matchLabels:
      component: cleanup-export
      app: exposure-notifications-server
  template:
    metadata:
      labels:
        component: cleanup-export
        app: exposure-notifications-server
    spec:
      containers:
      - name: cleanup-export
        image: {{ .Values.image.registry }}/cleanup-export:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pull_policy }}
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: "12m"
            memory: "100Mi"
          limits:
            cpu: "16m"
            memory: "200Mi"
        env:
          - name: PORT
            value: "8080"
          - name: CLEANUP_TIMEOUT
            value: "10m"
          - name: CLEANUP_TTL
            value: "336h"
{{ include "exposure-notification.observability-exporter" . | indent 10 }}
{{ include "exposure-notification.blob-storage" . | indent 10 }}
{{ include "exposure-notification.database" . | indent 10 }}
{{ include "exposure-notification.secrets-management" . | indent 10 }}
{{- if .Values.azure }}
{{ include "exposure-notification.azure-service-principal" . | indent 10 }}
{{- end }}
{{- end }}
