# blob store
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cleanup-exposure
  labels:
    component: cleanup-exposure
    app: exposure-notifications-server
spec:
  replicas: 1
  selector:
    matchLabels:
      component: cleanup-exposure
      app: exposure-notifications-server
  template:
    metadata:
      labels:
        component: cleanup-exposure
        app: exposure-notifications-server
    spec:
      containers:
      - name: cleanup-exposure
        image: {{ .Values.registry.host }}/{{ .Values.registry.org }}/cleanup-exposure:latest
        ports:
          - containerPort: 8080
        env:
          - name: PORT
            value: 8080
          - name: CLEANUP_TIMEOUT
            value: 10m
          - name: CLEANUP_TTL
            value: 336h
          # storage
          - name: BLOBSTORE
            value: AZURE_BLOB_STORAGE
          - name: AZURE_STORAGE_ACCOUNT
            value: {{ .Values.storageaccount.name }}
          - name: AZURE_STORAGE_ACCESS_KEY
            value: {{ .Values.storageaccount.accesskey }}
          # database
          - name: DB_NAME
            value: {{ .Values.psql.database.name }}
          - name: DB_USER
            valueFrom:
            secretKeyRef:
              name: {{ .Values.psql.server.name }}
              key: username
          - name: DB_HOST
            valueFrom:
            secretKeyRef:
              name: {{ .Values.psql.server.name }}
              key: fullyQualifiedServerName
          - name: DB_PORT
            value: 5432
          - name: DB_SSLMODE
            value: require
          - name: DB_CONNECT_TIMEOUT
            value: 30
          - name: DB_PASSWORD
            valueFrom:
            secretKeyRef:
              name: {{ .Values.psql.server.name }}
              key: password
          - name: DB_SSLCERT
            value: ""
          - name: DB_SSLKEY
            value: ""
          - name: DB_SSLROOTCERT
            value: ""
          - name: DB_POOL_MIN_CONNS
            value: ""
          - name: DB_POOL_MAX_CONNS
            value: ""
          - name: DB_POOL_MAX_CONN_LIFETIME
            value: ""     
          - name: DB_POOL_MAX_CONN_IDLE_TIME
            value: ""
          - name: DB_POOL_HEALTH_CHECK_PERIOD
            value: ""
          # secrets
          - name: AZURE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: AZURE_CLIENT_ID
                name: azureoperatorsettings
                optional: true
          - name: AZURE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                key: AZURE_CLIENT_SECRET
                name: azureoperatorsettings
                optional: true
          - name: AZURE_TENANT_ID
            valueFrom:
              secretKeyRef:
                key: AZURE_TENANT_ID
                name: azureoperatorsettings
          - name: AZURE_SUBSCRIPTION_ID
            valueFrom:
              secretKeyRef:
                key: AZURE_SUBSCRIPTION_ID
                name: azureoperatorsettings