{{- if .Values.export }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: export
  labels:
    component: export
    app: exposure-notifications-server
spec:
  replicas: 1
  selector:
    matchLabels:
      component: export
      app: exposure-notifications-server
  template:
    metadata:
      labels:
        component: export
        app: exposure-notifications-server
    spec:
      containers:
      - name: export
        image: {{ .Values.image.registry }}/export:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pull_policy | quote }}
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: "6m"
            memory: "100Mi"
          limits:
            cpu: "8m"
            memory: "200Mi"
        env:
          - name: PORT
            value: "8080"
          - name: CREATE_BATCHES_TIMEOUT
            value: "5m"
          - name: WORKER_TIMEOUT
            value: "5m"
          - name: EXPORT_FILE_MIN_RECORDS
            value: "1000"
          - name: EXPORT_FILE_PADDING_RANGE
            value: "100"
          - name: EXPORT_FILE_MAX_RECORDS
            value: "30000"
          - name: TRUNCATE_WINDOW
            value: "1h"
          - name: MIN_WINDOW_AGE
            value: "2h"
          - name: CLEANUP_TTL
            value: "336h"
{{ include "exposure-notification.observability-exporter" . | indent 10 }}
{{ include "exposure-notification.blob-storage" . | indent 10 }}
{{ include "exposure-notification.database" . | indent 10 }}
{{ include "exposure-notification.secrets-management" . | indent 10 }}
{{ include "exposure-notification.key-management" . | indent 10 }}
{{- if .Values.azure }}
{{ include "exposure-notification.azure-service-principal" . | indent 10 }}
{{- end }}
{{- end }}
