# blob store
apiVersion: apps/v1
kind: Deployment
metadata:
  name: export
  labels:
    component: export
    app: exposure-notifications-server
spec:
  replicas: 1
  selector:
    matchLabels:
      component: export
      app: exposure-notifications-server
  template:
    metadata:
      labels:
        component: export
        app: exposure-notifications-server
    spec:
      containers:
      - name: export
        image: {{ .Values.registry.host }}/{{ .Values.registry.org }}/export:latest
        ports:
          - containerPort: 8080
        env:
          - name: PORT
            value: 8080
          # storage
          - name: BLOBSTORE
            value: AZURE_BLOB_STORAGE
          - name: AZURE_STORAGE_ACCOUNT
            value: {{ .Values.storageaccount.name }}
          - name: AZURE_STORAGE_ACCESS_KEY
            value: {{ .Values.storageaccount.accesskey }}
          # database
          - name: DB_NAME
            value: {{ .Values.psql.database.name }}
          - name: DB_USER
            valueFrom:
            secretKeyRef:
              name: {{ .Values.psql.server.name }}
              key: username
          - name: DB_HOST
            valueFrom:
            secretKeyRef:
              name: {{ .Values.psql.server.name }}
              key: fullyQualifiedServerName
          - name: DB_PORT
            value: 5432
          - name: DB_SSLMODE
            value: require
          - name: DB_CONNECT_TIMEOUT
            value: 30
          - name: DB_PASSWORD
            valueFrom:
            secretKeyRef:
              name: {{ .Values.psql.server.name }}
              key: password
          - name: DB_SSLCERT
            value: ""
          - name: DB_SSLKEY
            value: ""
          - name: DB_SSLROOTCERT
            value: ""
          - name: DB_POOL_MIN_CONNS
            value: ""
          - name: DB_POOL_MAX_CONNS
            value: ""
          - name: DB_POOL_MAX_CONN_LIFETIME
            value: ""     
          - name: DB_POOL_MAX_CONN_IDLE_TIME
            value: ""
          - name: DB_POOL_HEALTH_CHECK_PERIOD
            value: ""
          # secrets
          - name: AZURE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: AZURE_CLIENT_ID
                name: azureoperatorsettings
                optional: true
          - name: AZURE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                key: AZURE_CLIENT_SECRET
                name: azureoperatorsettings
                optional: true
          - name: AZURE_TENANT_ID
            valueFrom:
              secretKeyRef:
                key: AZURE_TENANT_ID
                name: azureoperatorsettings
          - name: AZURE_SUBSCRIPTION_ID
            valueFrom:
              secretKeyRef:
                key: AZURE_SUBSCRIPTION_ID
                name: azureoperatorsettings
          # export specific
          - name: CREATE_BATCHES_TIMEOUT
            value: 5m
          - name: WORKER_TIMEOUT
            value: 5m
          - name: EXPORT_FILE_MIN_RECORDS
            value: 1000
          - name: EXPORT_FILE_PADDING_RANGE
            value: 100
          - name: EXPORT_FILE_MAX_RECORDS
            value: 30000
          - name: TRUNCATE_WINDOW
            value: 1h
          - name: MIN_WINDOW_AGE
            value: 2h
          - name: CLEANUP_TTL
            value: 336h
