{{- if .Values.exposure }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: exposure
  labels:
    component: exposure
    app: exposure-notifications-server
spec:
  replicas: 1
  selector:
    matchLabels:
      component: exposure
      app: exposure-notifications-server
  template:
    metadata:
      labels:
        component: exposure
        app: exposure-notifications-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: exposure
        image: {{ .Values.image.registry }}/exposure:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pull_policy }}
        ports:
          - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
          - name: TARGET_REQUEST_DURATION
            value: "5s"
          - name: MAX_KEYS_ON_PUBLISH
            value: "15"
          - name: MAX_INTERVAL_AGE_ON_PUBLISH
            value: "360h"
          - name: TRUNCATE_WINDOW
            value: "1h"
          # authorization
          - name: AUTHORIZED_APP_CACHE_DURATION
            value: "5m"
{{ include "exposure-notification.observability-exporter" . | indent 10 }}
{{ include "exposure-notification.database" . | indent 10 }}
{{ include "exposure-notification.secrets-management" . | indent 10 }}
{{- if .Values.azure }}
{{ include "exposure-notification.azure-service-principal" . | indent 10 }}
{{- end }}
{{- end }}
