{{- if .Values.generate }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: generate
  labels:
    component: generate
    app: exposure-notifications-server
spec:
  replicas: 1
  selector:
    matchLabels:
      component: generate
      app: exposure-notifications-server
  template:
    metadata:
      labels:
        component: generate
        app: exposure-notifications-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: generate
        image: {{ .Values.registry }}/export:latest
        ports:
          - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
          - name: OBSERVABILITY_EXPORTER
            value: "OCAGENT"
          - name: NUM_EXPOSURES_GENERATED
            value: "10"
          - name: KEYS_PER_EXPOSURE
            value: "14"
          - name: MAX_KEYS_ON_PUBLISH
            value: "15"
          - name: MAX_INTERVAL_AGE_ON_PUBLISH
            value: "360h"
          - name: TRUNCATE_WINDOW
            value: "1h"
          - name: DEFAULT_REGOIN
            value: "westus"
          # storage
          - name: BLOBSTORE
            value: "AZURE_BLOB_STORAGE"
          - name: AZURE_STORAGE_ACCOUNT
            value: {{ .Values.storageaccount.name | quote }}
          - name: AZURE_STORAGE_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: storageaccount-{{ .Values.resourcegroup.name }}-{{ .Values.storageaccount.name }}
                key: key1
          # database
          - name: DB_NAME
            value: {{ .Values.psql.database.name }}
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.psql.server.name }}
                key: fullyQualifiedUsername
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: {{ .Values.psql.server.name }}
                key: fullyQualifiedServerName
          - name: DB_PORT
            value: "5432"
          - name: DB_SSLMODE
            value: "require"
          - name: DB_CONNECT_TIMEOUT
            value: "30"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.psql.server.name }}
                key: password
          - name: DB_SSLCERT
            value: ""
          - name: DB_SSLKEY
            value: ""
          - name: DB_SSLROOTCERT
            value: ""
          - name: DB_POOL_MIN_CONNS
            value: ""
          - name: DB_POOL_MAX_CONNS
            value: ""
          # - name: DB_POOL_MAX_CONN_LIFETIME
          #   value: ""     
          # - name: DB_POOL_MAX_CONN_IDLE_TIME
          #   value: ""
          # - name: DB_POOL_HEALTH_CHECK_PERIOD
          #   value: ""
          # secrets
          - name: KEY_MANAGER
            value: "AZURE_KEY_VAULT"
          - name: SECRET_MANAGER
            value: "AZURE_KEY_VAULT"
          - name: AZURE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: AZURE_CLIENT_ID
                name: azureoperatorsettings
                optional: true
          - name: AZURE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                key: AZURE_CLIENT_SECRET
                name: azureoperatorsettings
                optional: true
          - name: AZURE_TENANT_ID
            valueFrom:
              secretKeyRef:
                key: AZURE_TENANT_ID
                name: azureoperatorsettings
          - name: AZURE_SUBSCRIPTION_ID
            valueFrom:
              secretKeyRef:
                key: AZURE_SUBSCRIPTION_ID
                name: azureoperatorsettings
{{- end }}
