{{- if and .Values.autoscaling .Values.export }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: export
  labels:
    component: export
    app: exposure-notifications-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: export
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
{{- end }}
