{{- if and .Values.autoscaling .Values.federation }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: federationin
  labels:
    component: federationin
    app: exposure-notifications-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: federationin
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
{{- end }}
