{{- if and .Values.autoscaling .Values.federation }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: federationout
  labels:
    component: federationout
    app: exposure-notifications-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: federationout
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
{{- end }}
