{{- if .Values.migrate }}
apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  labels:
    component: migrate
    app: exposure-notifications-server
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: {{ .Values.image.registry }}/migrate:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pull_policy | quote }}
        command: ["sh", "-c"]
        args:
        # escape the entire connection string so that special characters are handled and pass to the migrate command.
          - (DB_PASS=$(echo -n ${DB_PASSWORD} | hexdump -v -e '/1 "%02x"' | sed 's/\(..\)/%\1/g');
           /usr/local/bin/migrate -database "postgres://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE}" -path migrations up)
        resources:
          requests:
            cpu: "1m"
            memory: "40Mi"
          limits:
            cpu: "2m"
            memory: "80Mi"
        env:
{{ include "exposure-notification.database" . | indent 10 }}
      restartPolicy: Never
  backoffLimit: 4
{{- end }}
