apiVersion: azure.microsoft.com/v1alpha1
kind: PostgreSQLServer
metadata:
  name: {{ .Values.psql.server.name }}
spec:
  location: {{ .Values.region  }}
  resourceGroup: {{ .Values.resourcegroup.name }}
  serverVersion: "10"
  sslEnforcement: Enabled
  createMode: Default # Possible values include: Default, Replica, PointInTimeRestore (not implemented), GeoRestore (not implemented)
  sku:
    name: GP_Gen5_4       # Name - The name of the sku, typically, tier + family + cores, e.g. B_Gen4_1, GP_Gen5_8.
    tier: GeneralPurpose  # possible values - 'Basic', 'GeneralPurpose', 'MemoryOptimized'
    family: Gen5
    size: "51200"
    capacity: 4
  # Use the field below to optionally specify a different keyvault
  # to store the server admin credential secrets in
  #keyVaultToStoreSecrets: asoSecretKeyVault

---

apiVersion: azure.microsoft.com/v1alpha1
kind: PostgreSQLDatabase
metadata:
  name: {{ .Values.psql.database.name }}
spec:
  resourceGroup: {{ .Values.resourcegroup.name }}
  server: {{ .Values.psql.server.name }}

# ---

# apiVersion: azure.microsoft.com/v1alpha1
# kind: PostgreSQLVNetRule
# metadata:
#   name: postgresqlvnetrule-rule1
# spec:
#   resourceGroup: {{ .Values.resourcegroup.name }}
#   server: {{ .Values.psql.server.name }}
#   vNetResourceGroup: {{ .Values.resourcegroup.name }}
#   vNetName: {{ .Values.vnet.name }}
#   subnetName: {{ .Values.subnet.name }}
#   ignoreMissingServiceEndpoint: true
---
apiVersion: azure.microsoft.com/v1alpha1
kind: PostgreSQLFirewallRule
metadata:
  name: postgresqlfirewallrule
spec:
  resourceGroup: {{ .Values.resourcegroup.name }}
  server: {{ .Values.psql.server.name }}
  startIpAddress: 0.0.0.0
  endIpAddress: 0.0.0.0
