apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.azure.service_principal_secret | quote }}
type: Opaque
data:
  AZURE_SUBSCRIPTION_ID: {{ .Values.azure.subscription | b64enc | quote }}
  AZURE_TENANT_ID: {{ .Values.azure.tenant | b64enc | quote }}
  AZURE_CLOUD_ENV: {{ .Values.cloudEnvironment | default "AzurePublicCloud" | b64enc | quote }}

  {{- if .Values.azure.client_id }}
  AZURE_CLIENT_ID: {{ .Values.azure.client_id | b64enc | quote }}
  {{- end }}
  {{- if .Values.azureClientSecret }}
  AZURE_CLIENT_SECRET: {{ .Values.azure.client_secret | b64enc | quote }}
  {{- end }}
  {{- if .Values.azureUseMI }}
  AZURE_USE_MI: {{ "false" | b64enc | quote }}
  {{- end }}
