apiVersion: v1
kind: Service
metadata:
  name: export
  labels:
    component: export
    app: exposure-notifications-server
spec:
  selector:
    component: export
    app: exposure-notifications-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
