{{- if .Values.exposure.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: exposure
  labels:
    component: exposure
    app: exposure-notifications-server
spec:
  selector:
    component: exposure
    app: exposure-notifications-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
{{- end }}
