apiVersion: v1
kind: Service
metadata:
  name: cleanup-exposure
  labels:
    component: cleanup-exposure
    app: exposure-notifications-server
spec:
  selector:
    component: cleanup-exposure
    app: exposure-notifications-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
