{{- if .Values.adminConsole }}
apiVersion: v1
kind: Service
metadata:
  name: admin-console
  labels:
    component: admin-console
    app: exposure-notifications-server
spec:
  selector:
    component: admin-console
    app: exposure-notifications-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
{{- end }}
