{{- if and .Values.azure .Values.azure.vnet .Values.azure.vnet.aso }}
apiVersion: azure.microsoft.com/v1alpha1
kind: VirtualNetwork
metadata:
  name: {{ .Values.azure.vnet.name | quote }}
spec:
  location: {{ .Values.azure.region }}
  resourceGroup: {{ .Values.azure.resourcegroup.name | quote }}
  addressSpace: {{ .Values.azure.vnet.addressSpace | quote }}
  subnets:
    - subnetName: {{ .Values.azure.subnet.name | quote }}
      subnetAddressPrefix: {{ .Values.azure.subnet.addressPrefix | quote }}
      # Optional: enable service endpoints
      serviceEndpoints:
        - Microsoft.Storage
      # - Microsoft.Sql
{{- end }}
