# Default values for asodev.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

subscription: ""
registry: exposurenotificationsserver.azurecr.io

region: eastus

resourcegroup:
  name: rg-expotest-dev

keyvault:
  name: kv-expotest-dev

psql:
  server:
    name: srv-expotest-dev
  database:
    name: main

storageaccount:
  name: saexpotestdev

vnet:
  name: vnet-expotest-dev

subnet:
  name: test1

# services
cleanupExport: true
cleanupExposure: true
export: true
exposure: true
generate: true
federation: true
migrate: true
admin: true

# crons
schedule:
  exportBatches: "*/5 * * * *" #"*/5 * * * *"
  createBatches: "*/5 * * * *" #"*/5 * * * *"
  cleanupExport: "*/5 * * * *" #"0 */6 * * *"
  cleanupExposure: "*/5 * * * *" #"0 */4 * * *"