# Default values for asodev.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  registry: exposurenotificationsserver.azurecr.io
  tag: latest
  pull_policy: Always

blob_storage:
  type: AZURE_BLOB_STORAGE
  aso:
    account_name: saexpotestdev
    container_name: blobcontainer-sample

key_management:
  type: AZURE_KEY_VAULT
  aso:
    keyvault:
      name: kv-expo-keys
      key:
        name: kvk-expotest-dev
        type: EC
        curve: P-256
        operations:
        - sign

secrets_management:
  type: AZURE_KEY_VAULT
  aso:
    keyvault:
      name: kv-expo-secrets

database:
  db_name: main

  aso:
    psql:
      server_name: srv-expotest-dev
      server_version: "10"
      ssl_enforcement: Enabled
      sku:
        name: GP_Gen5_4 # Name - The name of the sku, typically, tier + family + cores, e.g. B_Gen4_1, GP_Gen5_8.
        tier: GeneralPurpose  # possible values - 'Basic', 'GeneralPurpose', 'MemoryOptimized'
        family: Gen5
        size: "51200"
        capacity: 4
      firewall:
        startIP: 0.0.0.0
        endIP: 0.0.0.0

observability_exporter:
  type: OCAGENT # possible values "OCAGENT", "STACKDRIVER"

azure:
  subscription: ""
  tenant: ""
  region: eastus
  resourcegroup:
    aso: true
    name: rg-expotest-dev
  subnet:
    name: test1
    addressPrefix: "10.1.0.0/16"
  vnet:
    aso: true
    name: vnet-expotest-dev
    addressSpace: "10.0.0.0/8"
  service_principal_secret: azureoperatorsettings

# services
cleanupExport: true
cleanupExposure: true
export: true
exposure:
  enabled: true
  ingress:
    enabled: true
    class: nginx
generate: true
federation: true
migrate: true
adminConsole: true

# crons
schedule:
  exportBatches: "*/5 * * * *" #"*/5 * * * *"
  createBatches: "*/5 * * * *" #"*/5 * * * *"
  cleanupExport: "*/5 * * * *" #"0 */6 * * *"
  cleanupExposure: "*/5 * * * *" #"0 */4 * * *"